[project]
name = "backend"
version = "0.1.0"
description = "Python backend with FastAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "python-dateutil",
]
